import { useLayoutEffect, useRef } from "react";
import { gsap } from "gsap/dist/gsap";
import useMousePosition from "@/hooks/useMousePosition";
import Head from "next/head";

export default function IndexPage() {
  const root = useRef();
  const mousePosition = useMousePosition();

  useLayoutEffect(() => {
    var width = window.innerWidth,
      height = window.innerHeight,
      positionX = (mousePosition.x / width) - 0.55,
      positionY = (mousePosition.y / height) - 0.55;
    console.log(height)
    gsap.to(".image_box img", {
      rotationY: positionX * 40,
      rotationX: positionY * 40,
      ease: "none"
    })

  }, [mousePosition]);

  return (
    <>
    
    <Head>
        <title>GSAP 3D</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="page" ref={root}>
      <div className="container">
        <div className="image_box">
          <img src={'/block.jpg'} />
        </div>
      </div>
    </div>
    </>
  );
}
